### ISSUE TITLE
win10 vs2019 python3.11.5E:\test\build\Release>python HelloWorldPublisher.py Starting publisher. [foonathan::memory] Allocator foonathan::memory::memory_pool (at 000002DB5AB14E88) received invalid size/alignment 24, max supported is 16 2024-08-20 10:47:23.410 [RTPS_MSG_OUT Error] allocation node size exceeds supported maximum of allocator -> Function eprosima::fastdds::rtps::SharedMemTransport::init 2024-08-20 10:47:23.410 [RTPS_PARTICIPANT Error] Unable to Register SHM Transport. SHM Transport is not supported in the current platform. -> Function eprosima::fastdds::rtps::RTPSParticipantImpl::setup_transports [foonathan::memory] Allocator foonathan::memory::memory_pool (at 000002DB5AB34BE0) received invalid size/alignment 64, max supported is 56

### ISSUE THREAD

**Issue by SunLiangcan** [eProsima/Fast-DDS-python#181]
E:\test\build\Release>python HelloWorldPublisher.py
Starting publisher.
[foonathan::memory] Allocator foonathan::memory::memory_pool (at 000002DB5AB14E88) received invalid size/alignment 24, max supported is 16
2024-08-20 10:47:23.410 [RTPS_MSG_OUT Error] allocation node size exceeds supported maximum of allocator -> Function eprosima::fastdds::rtps::SharedMemTransport::init
2024-08-20 10:47:23.410 [RTPS_PARTICIPANT Error] Unable to Register SHM Transport. SHM Transport is not supported in the current platform. -> Function eprosima::fastdds::rtps::RTPSParticipantImpl::setup_transports
[foonathan::memory] Allocator foonathan::memory::memory_pool (at 000002DB5AB34BE0) received invalid size/alignment 64, max supported is 56

**Comment by JesusPoderoso** [comment]
Hi @SunLiangcan, thanks for using Fast DDS Python.
I think we need more information to determine the root cause of your problem.
Could you provide the Fast DDS Python version that you have built?
Are you running the `fastdds_python_examples/HelloWorldExample`? Or is it an example generated with the Fast DDS-Gen tool (`fastddsgen -python -example CMake HelloWorld.idl`)?
Assuming that your machine runs win10 vs2019 python3.11.5, which architecture does it have? (x32 / x64)?

**Comment by SunLiangcan** [comment]
I have solved it. The solution is to modify the container_node_sizes_impl.hpp file
