### ISSUE TITLE
ModuleNotFoundError: No module named 'fastdds' [14511]

### ISSUE THREAD

**Issue by swapnildhalange** [eProsima/Fast-DDS-python#25]
I have followed every step mentioned in readme and while running the HelloWorld.py I'm getting module error

```
oot@c9cd7e55c125:/workspace/HelloWorld_build# python3.9 HelloWorld.py 
Traceback (most recent call last):
  File "/workspace/HelloWorld_build/HelloWorld.py", line 125, in <module>
    import fastdds
ModuleNotFoundError: No module named 'fastdds'
root@c9cd7e55c125:/workspace/HelloWorld_build# 
```

ls of build dir 

```
root@c9cd7e55c125:/workspace/HelloWorld_build# ls
CMakeCache.txt  CMakeFiles  HelloWorld.py  Makefile  _HelloWorldWrapper.so  cmake_install.cmake  libHelloWorld.so
```

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @swapnildhalange,

Thanks for your contribution! I agree that the README could be improved and in fact it is missing some points that someone used to `colcon` tool might overlook. The issue arises because you have not probably source the installation after executing `colcon build`. I am going to add this step into the README instructions. However, I suggest you look into [this tutorial](https://fast-dds.docs.eprosima.com/en/latest/fastdds/getting_started/simple_python_app/simple_python_app.html) which is more complete. In fact, the step the README is missing is just [here](https://fast-dds.docs.eprosima.com/en/latest/fastdds/getting_started/simple_python_app/simple_python_app.html#colcon-installation).

I hope this information is helpful

**Comment by JLBuenoLopez-eProsima** [comment]
I have created #27 to directly link to the documentation example which is the complete one.
